### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by sabowsla** [kyegomez/Andromeda#12]
just installing with python  3.11 

Collecting andromeda-torch
  Downloading andromeda_torch-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting SentencePiece (from andromeda-torch)
  Using cached sentencepiece-0.1.99-cp311-cp311-macosx_11_0_arm64.whl (1.2 MB)
Collecting accelerate (from andromeda-torch)
  Using cached accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)
Collecting datasets (from andromeda-torch)
  Using cached datasets-2.15.0-py3-none-any.whl.metadata (20 kB)
Collecting deepspeed (from andromeda-torch)
  Downloading deepspeed-0.12.5.tar.gz (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 2.1 MB/s eta 0:00:00a 0:00:010m
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/setup.py", line 38, in <module>
          from op_builder.all_ops import ALL_OPS
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/op_builder/all_ops.py", line 29, in <module>
          builder = get_accelerator().create_op_builder(member_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/accelerator/mps_accelerator.py", line 223, in create_op_builder
          builder_class = self.get_op_builder(op_name)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/accelerator/mps_accelerator.py", line 230, in get_op_builder
          from deepspeed.ops.op_builder.cpu import NotImplementedBuilder
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/deepspeed/__init__.py", line 21, in <module>
          from . import ops
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/deepspeed/ops/__init__.py", line 6, in <module>
          from . import adam
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/deepspeed/ops/adam/__init__.py", line 6, in <module>
          from .cpu_adam import DeepSpeedCPUAdam
        File "/private/var/folders/t5/559pccz52qx4d_x668tmzy1c0000gn/T/pip-install-n07wfbss/deepspeed_7e6217180e9a410bb375809b1bef1abb/deepspeed/ops/adam/cpu_adam.py", line 7, in <module>
          from cpuinfo import get_cpu_info
      ModuleNotFoundError: No module named 'cpuinfo'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/Andromeda/issues/12">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/Andromeda/issues/12/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/Andromeda/issues/12/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@sabowsla the error has been eliminated thank you for your report.
