### ISSUE TITLE
Build Dataset Script Fails

### ISSUE THREAD

**Issue by evannorstrand-mp** [kyegomez/Andromeda#2]
python3 Andromeda/build_dataset.py --seed 42 --seq_len 8192 --hf_account "<key>" --tokenizer "EleutherAI/gpt-neox-20b" --dataset_name "EleutherAI/the_pile_deduplicated"

Traceback (most recent call last):
  File "/home/ubuntu/Andromeda/Andromeda/build_dataset.py", line 70, in <module>
    built_dataset(args)
  File "/home/ubuntu/Andromeda/Andromeda/build_dataset.py", line 17, in built_dataset
    tokenizer = AutoTokenizer.from_pretrained(CFG.Tokenizer)
AttributeError: type object 'CFG' has no attribute 'Tokenizer'

**Comment by evannorstrand-mp** [comment]
CFG.Tokenizer should be CFG.TOKENIZER
